// utils/storagedCourses.ts

import { CourseCardProps } from '../components/courseCard';

export default function StoragedCourses(): CourseCardProps[] {
  return [
    // --- Saúde ---
    {
      title: "Técnico em Agente Comunitário de Saúde",
      subTitle: "Saúde",
      rating: 4.8,
      description: "Torne-se o elo vital entre a comunidade e os serviços de saúde, promovendo bem-estar e prevenção.",
      badge: "Essencial na Comunidade",
      img: {
        src: "",
        alt: "Profissional da saúde realizando visita domiciliar",
      },
    },
    {
      title: "Técnico em Análises Clínicas",
      subTitle: "Saúde",
      rating: 4.9,
      description: "Domine as técnicas laboratoriais essenciais para o diagnóstico preciso e o avanço da medicina.",
      badge: "Precisão e Cuidado",
      img: {
        src: "",
        alt: "Cientista em laboratório de análises clínicas com microscópio",
      },
    },
    {
      title: "Técnico em Cuidados de Idosos",
      subTitle: "Saúde",
      rating: 5,
      description: "Especialize-se no cuidado humanizado e na qualidade de vida da população idosa, um mercado em expansão.",
      badge: "Cuidado e Respeito",
      img: {
        src: "",
        alt: "Cuidador auxiliando uma pessoa idosa",
      },
    },
    {
      title: "Técnico em Enfermagem",
      subTitle: "Saúde",
      rating: 5,
      description: "Prepare-se para atuar na linha de frente do cuidado, com formação prática e humanizada.",
      badge: "Mais Procurado",
      img: {
        src: "",
        alt: "Técnica de enfermagem sorrindo em ambiente hospitalar",
      },
    },
    {
      title: "Técnico em Equipamentos Biomédicos",
      subTitle: "Saúde",
      rating: 4.7,
      description: "Seja o especialista por trás da tecnologia que salva vidas, garantindo o funcionamento de equipamentos hospitalares.",
      badge: "Tecnologia e Saúde",
      img: {
        src: "",
        alt: "Técnico realizando manutenção em equipamento biomédico",
      },
    },
    {
      title: "Técnico em Estética",
      subTitle: "Saúde",
      rating: 4.9,
      description: "Transforme o bem-estar e a autoestima das pessoas através de técnicas estéticas modernas e seguras.",
      badge: "Mercado Aquecido",
      img: {
        src: "",
        alt: "Profissional de estética realizando procedimento facial",
      },
    },
    {
      title: "Técnico em Farmácia",
      subTitle: "Saúde",
      rating: 4.8,
      description: "Atue no suporte essencial em farmácias e drogarias, garantindo a correta dispensação de medicamentos.",
      badge: "Cuidado Essencial",
      img: {
        src: "",
        alt: "Técnica em farmácia organizando medicamentos",
      },
    },
    {
      title: "Técnico em Gerência em Saúde",
      subTitle: "Saúde",
      rating: 4.9,
      description: "Prepare-se para liderar e administrar equipes e processos em clínicas, hospitais e unidades de saúde.",
      badge: "Liderança e Gestão",
      img: {
        src: "",
        alt: "Pessoas em reunião de gestão em um ambiente de saúde",
      },
    },
    {
      title: "Técnico em Nutrição e Dietética",
      subTitle: "Saúde",
      rating: 5,
      description: "Promova a saúde e a qualidade de vida através da alimentação, elaborando planos nutricionais e cardápios.",
      badge: "Vida Saudável",
      img: {
        src: "",
        alt: "Nutricionista com prato de comida saudável",
      },
    },
    {
      title: "Técnico em Radiologia",
      subTitle: "Saúde",
      rating: 5,
      description: "Opere equipamentos de diagnóstico por imagem, sendo fundamental para a descoberta e tratamento de doenças.",
      badge: "Alta Tecnologia",
      img: {
        src: "",
        alt: "Técnico em radiologia operando máquina de raio-x",
      },
    },
    {
      title: "Técnico em Saúde Bucal",
      subTitle: "Saúde",
      rating: 4.8,
      description: "Atue ao lado de dentistas na promoção da saúde bucal, prevenção de doenças e em procedimentos clínicos.",
      badge: "Sorriso e Cuidado",
      img: {
        src: "",
        alt: "Assistente de saúde bucal auxiliando dentista",
      },
    },
    {
      title: "Técnico em Veterinária",
      subTitle: "Saúde",
      rating: 5,
      description: "Dedique-se ao cuidado e bem-estar dos animais, auxiliando médicos veterinários em clínicas e hospitais.",
      badge: "Paixão Animal",
      img: {
        src: "",
        alt: "Técnico em veterinária cuidando de um cachorro",
      },
    },
    {
      title: "Técnico em Administração",
      subTitle: "Finanças",
      rating: 5,
      description: "Desenvolva uma visão estratégica de negócios e prepare-se para organizar, gerir e liderar em qualquer setor.",
      badge: "Base para o Sucesso",
      img: {
        src: "",
        alt: "Equipe de administração em reunião de planejamento",
      },
    },
    {
      title: "Técnico em Contabilidade",
      subTitle: "Finanças",
      rating: 4.9,
      description: "Seja o profissional que garante a saúde financeira das empresas, dominando a organização de contas e tributos.",
      badge: "Organização e Precisão",
      img: {
        src: "",
        alt: "Pessoa trabalhando com calculadora e planilhas de contabilidade",
      },
    },
    {
      title: "Técnico em Marketing",
      subTitle: "Finanças",
      rating: 4.8,
      description: "Aprenda a criar estratégias de divulgação, fortalecer marcas e impulsionar vendas no mercado digital e físico.",
      badge: "Criatividade e Estratégia",
      img: {
        src: "",
        alt: "Gráficos e dados em uma apresentação de marketing",
      },
    },
    {
      title: "Técnico em Qualidade",
      subTitle: "Serviços Gerais",
      rating: 4.7,
      description: "Garanta a excelência em produtos e serviços, implementando e monitorando padrões de qualidade.",
      badge: "Padrão de Excelência",
      img: {
        src: "",
        alt: "Inspetor de qualidade analisando produto em uma fábrica",
      },
    },
    {
      title: "Técnico em Recursos Humanos",
      subTitle: "Finanças",
      rating: 4.9,
      description: "Especialize-se na gestão de pessoas, desde a seleção e treinamento até o desenvolvimento de talentos.",
      badge: "Gestão de Pessoas",
      img: {
        src: "",
        alt: "Profissional de recursos humanos em uma entrevista de emprego",
      },
    },
    {
      title: "Técnico em Secretaria Escolar",
      subTitle: "Serviços Gerais",
      rating: 4.8,
      description: "Seja a peça-chave na organização e administração de instituições de ensino, garantindo o bom funcionamento.",
      badge: "Organização Essencial",
      img: {
        src: "",
        alt: "Ambiente de uma secretaria escolar com arquivos e computador",
      },
    },
    {
      title: "Técnico em Segurança do Trabalho",
      subTitle: "Infraestrutura",
      rating: 5,
      description: "Torne-se um profissional indispensável, garantindo a segurança e o bem-estar em ambientes de trabalho.",
      badge: "Essencial",
      img: {
        src: "",
        alt: "Técnico de segurança do trabalho com capacete em uma obra",
      },
    },
    {
      title: "Técnico em Serviços Jurídicos",
      subTitle: "Serviços Gerais",
      rating: 4.7,
      description: "Atue no suporte administrativo e processual de escritórios de advocacia, cartórios e departamentos jurídicos.",
      badge: "Suporte Jurídico",
      img: {
        src: "",
        alt: "Pessoa trabalhando em um escritório de advocacia com livros de direito",
      },
    },
    {
      title: "Técnico em Transações Imobiliárias",
      subTitle: "Finanças",
      rating: 4.7,
      description: "Torne-se um corretor de imóveis qualificado, pronto para intermediar negociações de compra, venda e aluguel.",
      badge: "Mercado Imobiliário",
      img: {
        src: "",
        alt: "Corretor de imóveis entregando as chaves de uma casa",
      },
    },
    {
      title: "Técnico em Vendas",
      subTitle: "Finanças",
      rating: 4.8,
      description: "Domine as técnicas de negociação e persuasão para se tornar um vendedor de alta performance.",
      badge: "Foco em Resultados",
      img: {
        src: "",
        alt: "Vendedor atendendo cliente em uma loja",
      },
    },
    {
      title: "Curso Técnico em Eventos",
      subTitle: "Serviços Gerais",
      rating: 4.9,
      description: "Aprenda a planejar, organizar e executar eventos de sucesso, de pequenas reuniões a grandes conferências.",
      badge: "Momentos Inesquecíveis",
      img: {
        src: "",
        alt: "Organizador de eventos coordenando uma conferência",
      },
    },
    {
      title: "Técnico em Biotecnologia",
      subTitle: "Tecnologia",
      rating: 5,
      description: "Trabalhe na fronteira da ciência, aplicando conhecimentos biológicos em processos industriais e de saúde.",
      badge: "Nova Fronteira",
      img: {
        src: "",
        alt: "Cientista trabalhando com amostras em laboratório de biotecnologia",
      },
    },
    {
      title: "Técnico em Design Gráfico",
      subTitle: "Tecnologia",
      rating: 4.9,
      description: "Dê vida a ideias através de imagens, tipografia e elementos visuais para comunicação digital e impressa.",
      badge: "Criatividade Visual",
      img: {
        src: "",
        alt: "Designer gráfico trabalhando em um computador com software de edição",
      },
    },
    {
      title: "Técnico em Desenvolvimento de Sistemas",
      subTitle: "Tecnologia",
      rating: 5,
      description: "Aprenda a criar os softwares e aplicativos que movem o mundo digital, do design à implementação.",
      badge: "Alta Empregabilidade",
      img: {
        src: "",
        alt: "Desenvolvedor de sistemas programando com código na tela",
      },
    },
    {
      title: "Técnico em Informática para Internet",
      subTitle: "Tecnologia",
      rating: 4.8,
      description: "Especialize-se na criação e manutenção de websites, portais e aplicações para a internet.",
      badge: "Construindo a Web",
      img: {
        src: "",
        alt: "Profissional de informática para internet criando um website",
      },
    },
    {
      title: "Técnico em Redes de Computadores",
      subTitle: "Tecnologia",
      rating: 4.9,
      description: "Garanta a conectividade e a segurança de sistemas, implementando e gerenciando infraestruturas de redes.",
      badge: "Mundo Conectado",
      img: {
        src: "",
        alt: "Técnico de redes trabalhando em um data center com servidores",
      },
    },
    {
      title: "Técnico em Sistemas de Energia Renovável",
      subTitle: "Tecnologia",
      rating: 5,
      description: "Faça parte da revolução energética, projetando e instalando sistemas de energia limpa como a solar e eólica.",
      badge: "Futuro Sustentável",
      img: {
        src: "",
        alt: "Técnico instalando painéis solares em um telhado",
      },
    },
    {
      title: "Técnico em Telecomunicações",
      subTitle: "Tecnologia",
      rating: 4.7,
      description: "Atue na instalação e manutenção de sistemas de comunicação que conectam o mundo.",
      badge: "Comunicação Global",
      img: {
        src: "",
        alt: "Técnico trabalhando em uma torre de telecomunicações",
      },
    },
    {
      title: "Técnico em Tradução e Interpretação de Libras",
      subTitle: "Serviços Gerais",
      rating: 5,
      description: "Promova a inclusão e a acessibilidade, tornando-se um profissional essencial na comunicação com a comunidade surda.",
      badge: "Conectando Mundos",
      img: {
        src: "",
        alt: "Mãos fazendo um sinal da Língua Brasileira de Sinais (Libras)",
      },
    },
    {
      title: "Técnico em Automação Industrial",
      subTitle: "Infraestrutura",
      rating: 4.9,
      description: "Projete e opere os sistemas robóticos e automatizados que movem a indústria moderna.",
      badge: "Indústria 4.0",
      img: {
        src: "",
        alt: "Braço robótico em uma linha de produção industrial automatizada",
      },
    },
    {
      title: "Técnico em Eletromecânica",
      subTitle: "Infraestrutura",
      rating: 4.8,
      description: "Integre conhecimentos de mecânica e eletricidade para atuar na montagem e manutenção de sistemas industriais.",
      badge: "Força e Energia",
      img: {
        src: "",
        alt: "Técnico em eletromecânica trabalhando em um motor industrial",
      },
    },
    {
      title: "Técnico em Eletrotécnica",
      subTitle: "Infraestrutura",
      rating: 4.8,
      description: "Domine projetos, instalações e manutenções de sistemas elétricos prediais e industriais com segurança.",
      badge: "Energia em Ação",
      img: {
        src: "",
        alt: "Eletricista trabalhando em um painel elétrico de alta tensão",
      },
    },
    {
      title: "Técnico em Eletrônica",
      subTitle: "Infraestrutura",
      rating: 4.7,
      description: "Aprenda a desenvolver, instalar e reparar circuitos e equipamentos eletrônicos de diversos tipos.",
      badge: "Inovação em Circuitos",
      img: {
        src: "",
        alt: "Técnico em eletrônica soldando componentes em uma placa de circuito",
      },
    },
    {
      title: "Técnico em Manutenção de Máquinas Industriais",
      subTitle: "Infraestrutura",
      rating: 4.9,
      description: "Seja o especialista que mantém a indústria em pleno funcionamento, prevenindo falhas e otimizando processos.",
      badge: "Indústria em Movimento",
      img: {
        src: "",
        alt: "Mecânico realizando manutenção em uma máquina industrial pesada",
      },
    },
    {
      title: "Técnico em Máquinas Pesadas",
      subTitle: "Infraestrutura",
      rating: 4.8,
      description: "Capacite-se para operar e realizar a manutenção de grandes equipamentos usados na construção e mineração.",
      badge: "Força e Precisão",
      img: {
        src: "",
        alt: "Operador em uma escavadeira em um canteiro de obras",
      },
    },
    {
      title: "Técnico em Metalurgia",
      subTitle: "Infraestrutura",
      rating: 4.7,
      description: "Aprenda sobre os processos de extração, transformação e aplicação de metais na indústria de base.",
      badge: "Transformando Metais",
      img: {
        src: "",
        alt: "Trabalhador em uma siderúrgica com metal derretido",
      },
    },
    {
      title: "Técnico em Refrigeração e Climatização",
      subTitle: "Infraestrutura",
      rating: 4.9,
      description: "Instale e realize a manutenção de sistemas de ar-condicionado e refrigeração em residências e indústrias.",
      badge: "Conforto e Tecnologia",
      img: {
        src: "",
        alt: "Técnico realizando manutenção em uma unidade de ar condicionado",
      },
    },
    {
      title: "Técnico em Soldagem",
      subTitle: "Infraestrutura",
      rating: 4.8,
      description: "Domine as técnicas para unir estruturas metálicas com precisão e segurança, um trabalho fundamental na indústria.",
      badge: "Unindo Estruturas",
      img: {
        src: "",
        alt: "Soldador com máscara de proteção trabalhando em estrutura metálica",
      },
    },
    {
      title: "Técnico em Manutenção de Máquinas Navais",
      subTitle: "Infraestrutura",
      rating: 4.9,
      description: "Especialize-se na manutenção de motores e sistemas de embarcações, garantindo segurança e performance.",
      badge: "Navegando com Segurança",
      img: {
        src: "",
        alt: "Engenheiro naval trabalhando na sala de máquinas de um navio",
      },
    },
    {
      title: "Técnico em Agrimensura",
      subTitle: "Infraestrutura",
      rating: 4.7,
      description: "Realize medições e levantamentos topográficos de terrenos, sendo essencial para projetos de engenharia e construção.",
      badge: "Mapeando o Futuro",
      img: {
        src: "",
        alt: "Agrimensor utilizando um teodolito em um campo",
      },
    },
    {
      title: "Técnico em Edificações",
      subTitle: "Infraestrutura",
      rating: 4.9,
      description: "Participe de todas as etapas de uma obra, do planejamento e desenho à execução e controle de qualidade.",
      badge: "Construindo o Futuro",
      img: {
        src: "",
        alt: "Técnico em edificações analisando a planta de uma construção",
      },
    },
    {
      title: "Técnico em Mineração",
      subTitle: "Infraestrutura",
      rating: 4.8,
      description: "Atue nos processos de extração e beneficiamento de minérios com foco em segurança e sustentabilidade.",
      badge: "Riqueza da Terra",
      img: {
        src: "",
        alt: "Minerador com capacete e lanterna em uma mina",
      },
    },
    {
      title: "Técnico em Prevenção e Combate ao Incêndio",
      subTitle: "Infraestrutura",
      rating: 5,
      description: "Capacite-se para atuar como bombeiro civil, protegendo vidas e patrimônios em situações de emergência.",
      badge: "Segurança em Primeiro Lugar",
      img: {
        src: "",
        alt: "Bombeiro em ação combatendo um incêndio",
      },
    },
    {
      title: "Curso Técnico em Defesa Civil",
      subTitle: "Infraestrutura",
      rating: 4.9,
      description: "Aprenda a prevenir e atuar em situações de desastres, protegendo a comunidade e o meio ambiente.",
      badge: "Protegendo Comunidades",
      img: {
        src: "",
        alt: "Agente da defesa civil em uma área de desastre",
      },
    },
    {
      title: "Curso Técnico em Trânsito",
      subTitle: "Infraestrutura",
      rating: 4.7,
      description: "Atue no planejamento, operação e fiscalização do trânsito para garantir a segurança e a mobilidade urbana.",
      badge: "Mobilidade e Segurança",
      img: {
        src: "",
        alt: "Agente de trânsito organizando o fluxo de veículos em uma cidade",
      },
    },
    {
      title: "Técnico em Agricultura",
      subTitle: "Meio Ambiente",
      rating: 4.8,
      description: "Aprenda sobre o cultivo do solo, manejo de culturas e gestão da produção agrícola de forma sustentável.",
      badge: "Cultivando o Futuro",
      img: {
        src: "",
        alt: "Agricultor analisando a colheita em um campo de cultivo",
      },
    },
    {
      title: "Técnico em Agropecuária",
      subTitle: "Meio Ambiente",
      rating: 4.9,
      description: "Gerencie de forma integrada a produção agrícola e a criação de animais, visando a produtividade e sustentabilidade.",
      badge: "Campo e Produção",
      img: {
        src: "",
        alt: "Técnico agropecuário cuidando do gado em um pasto",
      },
    },
    {
      title: "Técnico em Agroindústria",
      subTitle: "Meio Ambiente",
      rating: 4.8,
      description: "Atue no processamento e industrialização de matérias-primas de origem animal e vegetal.",
      badge: "Do Campo à Mesa",
      img: {
        src: "",
        alt: "Linha de produção e processamento de alimentos em uma agroindústria",
      },
    },
    {
      title: "Técnico em Aquicultura",
      subTitle: "Meio Ambiente",
      rating: 4.7,
      description: "Aprenda a cultivar peixes, crustáceos e outros organismos aquáticos de forma sustentável e produtiva.",
      badge: "Cultivando Águas",
      img: {
        src: "",
        alt: "Técnico em aquicultura trabalhando em tanques de criação de peixes",
      },
    },
    {
      title: "Técnico em Meio Ambiente",
      subTitle: "Meio Ambiente",
      rating: 5,
      description: "Atue na preservação dos recursos naturais, gestão de resíduos e desenvolvimento de projetos sustentáveis.",
      badge: "Planeta em Foco",
      img: {
        src: "",
        alt: "Técnico em meio ambiente coletando amostra de água em um rio",
      },
    },
    {
      title: "Técnico em Gastronomia",
      subTitle: "Serviços Gerais",
      rating: 5,
      description: "Transforme sua paixão pela culinária em uma carreira de sucesso, dominando técnicas e sabores.",
      badge: "Carreira Saborosa",
      img: {
        src: "",
        alt: "Chef de cozinha preparando um prato gourmet",
      },
    },
    {
      title: "Técnico em Óptica",
      subTitle: "Serviços Gerais",
      rating: 4.8,
      description: "Atue no mercado de saúde visual, confeccionando, consertando e adaptando óculos e lentes de contato.",
      badge: "Visão e Precisão",
      img: {
        src: "",
        alt: "Técnico em óptica ajustando um par de óculos",
      },
    },
    {
      title: "Curso Técnico em Designer de Interiores",
      subTitle: "Serviços Gerais",
      rating: 4.9,
      description: "Crie espaços funcionais, confortáveis e esteticamente agradáveis, transformando ambientes e vidas.",
      badge: "Criatividade e Espaço",
      img: {
        src: "",
        alt: "Ambiente de sala de estar moderno e bem decorado",
      },
    },
    {
      title: "Curso Técnico no Guia em Turismo",
      subTitle: "Serviços Gerais",
      rating: 4.8,
      description: "Conduza visitantes por roteiros turísticos, compartilhando cultura, história e informações sobre os destinos.",
      badge: "Explorando Destinos",
      img: {
        src: "",
        alt: "Guia de turismo orientando um grupo de turistas em um ponto turístico",
      },
    },
  ];
}